"""
    BIO Project

    Authors:    Ivana Saranová
                Radek Duchoň
    File:       config.py
    Date:       12. 12. 2020
"""


DATASET_FOLDER = 'dataset'
HEAD_FOLDER = 'head'
DATASET_IMG_SIZE = 1000
CLEAN_FRONT_PNG_NAME = 'p0.0_y0.0_r0.0.png'

DATASET_IMG_SIZE_HALF = DATASET_IMG_SIZE // 2 - 1
MIDDLE_POINT = (DATASET_IMG_SIZE_HALF, DATASET_IMG_SIZE_HALF)
TOP_MIDDLE_POINT = (DATASET_IMG_SIZE_HALF, 0)
BOTTOM_MIDDLE_POINT = (DATASET_IMG_SIZE_HALF, DATASET_IMG_SIZE - 1)

RIGHT_EYEBROW = range(17, 22)
LEFT_EYEBROW = range(22, 27)
NOSE_BRIDGE = range(27, 30)
NOSE_TIP = range(30, 36)
RIGHT_EYE = range(36, 42)
LEFT_EYE = range(42, 48)
MOUTH = range(48, 68)

SELION = 27
PRONASALE = 30
SUBNASALE = 33

ENCA_L = 42
ENCA_R = 39
EXCA_L = 45
EXCA_R = 36

MENTON = 8
GONION_L = 12
GONION_R = 4

MEAN_SELION_TO_BACK_HEAD = (197 + 189) / 2
MEAN_BIOCULAR_BREADTH = (122 + 116) / 2

MEAN_SELION_TOP_HEAD = (112 + 105) / 2
MEAN_MENTON_TOP_HEAD = (232 + 218) / 2
MEAN_SELION_MENTON = MEAN_MENTON_TOP_HEAD - MEAN_SELION_TOP_HEAD

MIDDLE_NOSE = 29
MEAN_SELION_MIDDLE_NOSE = (103 + 99) / 2 / 2
MEAN_MIDDLE_NOSE_MENTON = MEAN_SELION_MENTON - MEAN_SELION_MIDDLE_NOSE
